Picture-Blog-master/routes/web.php
<?php

use Illuminate\Support\Facades\Route;


// UserAccount
Route::group(['namespace' => 'UserAccount'], function () {

    //Login
    Route::get('/logout', 'SignInController@logout')->name('logout');
    Route::get('/signin', 'SignInController@index')->name('signin.index');
    Route::post('/signin', 'SignInController@signIn')->name('sigin');
    Route::get('/register', "RegisterController@show")->name("register.show");
    Route::post('/register', "RegisterController@register")->name("register");
    //Post Routes
    Route::resource('admin/post', 'PostController');


    Route::middleware('checkLogin')->group(function () {
        Route::prefix('user')->group(function () {

            //Controller Post of UserAcount
            Route::get('/{id}/delete', 'UsersAccountController@delete')->name('admin.User.delete');
            Route::get('post/show', 'UsersAccountController@showUserAll')->name('PostAll');
            Route::get('/post/private', 'UsersAccountController@showUserPrivate')->name('PostPrivate');
            Route::get('/post/public', 'UsersAccountController@showUserPublic')->name('PostPublic');
            Route::get('/post/create', 'UsersAccountController@PostCreate')->name('UserPost');
            Route::get('/post/{id}/edit', 'UsersAccountController@PostEdit')->name('PostEdit');


            //Controller Profile Edit
            Route::get('/profile/edit', 'UsersAccountController@ProfileEdit')->name('user.porfile.edit');
            Route::post('/profile/update', 'UsersAccountController@ProfileUpdate')->name('user.profile.update');

        });
    });

});


//User
Route::group(['namespace' => 'User'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('post/{post}', 'PostController@post')->name('post');
    Route::get('post/tag/{slug}', 'HomeController@tag')->name('tag');
    Route::get('post/category/{category}', 'HomeController@category')->name('category');
    Route::get('userdetail/{id}', 'PostController@showUserDetail')->name('user.detail');
});


//Admin
Route::middleware('checkLogin')->group(function () {
    Route::group(['namespace' => 'Admin'], function () {

        Route::get('admin/home', 'AdminController@index')->name('admin.home');
        //User Routes
        Route::resource('admin/user', 'UserController');

        //Tag Routes
        Route::resource('admin/tag', 'TagController');
        //Category Routes
        Route::resource('admin/category', 'CategoryController');
    });
});

Picture-Blog-master/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Picture-Blog-master/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Services\UsersService;
use App\Model\user\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $users = User::all();
        return view('admin.User.list', compact('users'));
    }

    public function create()
    {

        return view('admin.User.create');
    }

}

Picture-Blog-master/app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Model\user\category;
use App\Model\user\category_post;
use App\Model\user\post;
use App\Model\user\tag;
use App\Model\user\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HomeController extends Controller
{
    public function index(User $user){
//        $user = Auth::user();
        $posts = post::where('status',1)->orderBy('created_at','DESC')->paginate(6);
//        $postCate = $category->posts();

        $postLichsu= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'lich-su')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postChinhtri= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'chinh-tri')
            ->where('status',1)
            ->inRandomOrder()
            ->first();


        $postDoisong= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'doi-song')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postSuckhoe= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'suc-khoe')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postTintuc= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'suc-khoe')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postGiaitri= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'giai-tri')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postDulich= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'du-lich')
            ->where('status',1)
            ->inRandomOrder()
            ->first();
//        dd($user::findOrFail(1)->posts()->get());
//      $postUser = $user->posts()->get();
//        dd($postUser);

        return view('user.blog', compact('posts','postLichsu','postChinhtri','postDoisong','postSuckhoe','postTintuc','postDulich','postGiaitri'));
    }

    public function tag(tag $tag, $slug){


        $posts= DB::table('tags')->where('tags.slug','=',$slug)->posts();
        dd($posts);
        return view('user.category', compact('posts'));

    }

    public function category(category $category){

        $posts= $category->posts();

        return view('user.category', compact('posts','category'));

    }

    public function user(User $user){



    }
}

Picture-Blog-master/app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Model\user\post;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostController extends Controller
{
    public function post(post $post)
    {
//        $user= DB::table('users')
//            ->join('posts', 'users.id', '=', 'post.user_id')
//            ->where('users.id', $post->user_id)
//            ->first();
       $user =  DB::table('users')->where('id', $post->user_id)->get();


        $postLichsu= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'lich-su')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postChinhtri= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'chinh-tri')
            ->where('status',1)
            ->inRandomOrder()
            ->first();


        $postDoisong= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'doi-song')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postSuckhoe= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'suc-khoe')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postTintuc= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'suc-khoe')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postGiaitri= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'giai-tri')
            ->where('status',1)
            ->inRandomOrder()
            ->first();

        $postDulich= DB::table('category_posts')
            ->join('categories', 'category_posts.category_id', '=', 'categories.id')
            ->join('posts', 'category_posts.post_id', '=', 'posts.id')
            ->where('categories.slug', '=', 'du-lich')
            ->where('status',1)
            ->inRandomOrder()
            ->first();



        return view('user.post',compact('post','user','postDoisong','postTintuc','postSuckhoe','postChinhtri','postLichsu','postDulich','postGiaitri'));
    }

    public function showUserDetail($id)
    {

        $posts = \App\Model\user\User::findOrFail($id)->posts()->where('status', 1)->get();
        $user =  DB::table('users')->where('id', $id)->first();

        return view('user.userdetail',compact('user','posts'));

    }



}

Picture-Blog-master/resources/views/admin/User/create.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Create User
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">User</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <!-- general form elements -->
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="{{route('user.store')}}" enctype="multipart/form-data" >
                            @csrf
                            <div class="box-body">

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="title">Name</label>
                                        <input type="text" class="form-control" id="title" name="name" placeholder="Title">
                                    </div>

                                    <div class="form-group">
                                        <label for="subtitle">Email</label>
                                        <input type="text" class="form-control" id="subtitle" name="email" placeholder="">
                                    </div>

                                    <div class="form-group">
                                        <label for="slug">Password</label>
                                        <input type="password" class="form-control" id="slug" name="password" placeholder="">
                                    </div>

                                    <div class="form-group">
                                        <label for="slug">Avatar</label>
                                        <input type="file" class="form-control" id="" name="avatar" placeholder="">
                                    </div>

                                    <div class="form-group">
                                        <label for="slug">Role</label>
                                        <input type="text" class="form-control" id="slug" name="role" placeholder="">
                                    </div>
                                </div>



                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->


                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

Picture-Blog-master/resources/views/admin/User/list.blade.php
@extends('admin.layouts.app')

@section('headSection')
{{--    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">--}}
@endsection
@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Blank page
                <small>it all starts here</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">User</h3>
                    <a class='col-lg-offset-5 btn btn-success' href="{{ route('user.create') }}">Add New </a>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="box">
                        <div class="box-header">
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Create at</th>
                                    <th>Avatar</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $loop->index + 1 }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->created_at }}</td>
                                        <td><img src="{{asset("storage/images/".$user->avatar)}}" alt="No image"
                                                 style="height: 100px"></td>
                                        <td>
                                            <form id="delete-form-{{ $user->id }}" method="get" action="{{ route('admin.User.delete',$user->id) }}" style="display: none">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                            <a href="" onclick="
                                                if(confirm('Are you sure, You Want to delete this?'))
                                                {
                                                event.preventDefault();
                                                document.getElementById('delete-form-{{ $user->id }}').submit();
                                                }
                                                else{
                                                event.preventDefault();
                                                }" ><span class="glyphicon glyphicon-trash"></span></a>
                                        </td>
                                        {{--                                        <td><a href="{{ route('post.edit',$post->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>--}}
{{--                                        <td>--}}
{{--                                            <form id="delete-form-{{ $post->id }}" method="post" action="{{ route('post.destroy',$post->id) }}" style="display: none">--}}
{{--                                                {{ csrf_field() }}--}}
{{--                                                {{ method_field('DELETE') }}--}}
{{--                                            </form>--}}
{{--                                            <a href="" onclick="--}}
{{--                                                if(confirm('Are you sure, You Want to delete this?'))--}}
{{--                                                {--}}
{{--                                                event.preventDefault();--}}
{{--                                                document.getElementById('delete-form-{{ $post->id }}').submit();--}}
{{--                                                }--}}
{{--                                                else{--}}
{{--                                                event.preventDefault();--}}
{{--                                                }" ><span class="glyphicon glyphicon-trash"></span></a>--}}
{{--                                        </td>--}}
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection
@section('footerSection')
    <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $("#example1").DataTable();
        });
    </script>
@endsection